FROM node:22-slim

WORKDIR /app/frontend
COPY frontend/package.json frontend/pnpm-lock.yaml* /app/frontend/
RUN corepack enable && pnpm install --frozen-lockfile
COPY frontend /app/frontend
EXPOSE 5173
CMD ["pnpm", "run", "dev"]
